/**
 * Centralized Query Keys for TanStack Query
 * Enables predictable query invalidation and optimistic updates across modules.
 */

export const queryKeys = {
  auth: {
    me: ['auth', 'me'] as const,
  },
  dashboard: {
    stats: ['dashboard', 'stats'] as const,
    recentOrders: ['dashboard', 'recent-orders'] as const,
    recentCustomers: ['dashboard', 'recent-customers'] as const,
    recentReviews: ['dashboard', 'recent-reviews'] as const,
    lowStock: ['dashboard', 'low-stock'] as const,
    activity: ['dashboard', 'activity'] as const,
  },
  orders: {
    all: ['orders'] as const,
    lists: () => ['orders', 'list'] as const,
    list: (params?: Record<string, any>) => ['orders', 'list', params] as const,
    detail: (id: string) => ['orders', 'detail', id] as const,
  },
  products: {
    all: ['products'] as const,
    lists: () => ['products', 'list'] as const,
    list: (params?: Record<string, any>) => ['products', 'list', params] as const,
    detail: (id: string) => ['products', 'detail', id] as const,
    lowStock: () => ['products', 'low-stock'] as const,
    attributes: (id: string) => ['products', 'attributes', id] as const,
    collections: (id: string) => ['products', 'collections', id] as const,
    media: (id: string) => ['products', 'media', id] as const,
    options: (id: string) => ['products', 'options', id] as const,
    variants: (id: string) => ['products', 'variants', id] as const,
    seo: (id: string) => ['products', 'seo', id] as const,
  },
  customers: {
    all: ['customers'] as const,
    lists: () => ['customers', 'list'] as const,
    list: (params?: Record<string, any>) => ['customers', 'list', params] as const,
    detail: (id: string) => ['customers', 'detail', id] as const,
  },
  reviews: {
    all: ['reviews'] as const,
    lists: () => ['reviews', 'list'] as const,
    list: (params?: Record<string, any>) => ['reviews', 'list', params] as const,
    detail: (id: string) => ['reviews', 'detail', id] as const,
  },
  categories: {
    all: ['categories'] as const,
    tree: ['categories', 'tree'] as const,
    lists: () => ['categories', 'list'] as const,
    list: (params?: Record<string, any>) => ['categories', 'list', params] as const,
    detail: (id: string) => ['categories', 'detail', id] as const,
    children: (id: string) => ['categories', 'children', id] as const,
    ancestors: (id: string) => ['categories', 'ancestors', id] as const,
    attributes: (categoryId: string) => ['categories', 'attributes', categoryId] as const,
    filters: (slug: string) => ['categories', 'filters', slug] as const,
  },
  collections: {
    all: ['collections'] as const,
    lists: () => ['collections', 'list'] as const,
    list: (params?: Record<string, any>) => ['collections', 'list', params] as const,
    detail: (id: string) => ['collections', 'detail', id] as const,
    products: (id: string, params?: Record<string, any>) =>
      ['collections', 'products', id, params] as const,
    media: (id: string) => ['collections', 'media', id] as const,
  },
  attributes: {
    all: ['attributes'] as const,
    lists: () => ['attributes', 'list'] as const,
    list: (params?: Record<string, any>) => ['attributes', 'list', params] as const,
    detail: (id: string) => ['attributes', 'detail', id] as const,
    values: (attributeId: string) => ['attributes', 'values', attributeId] as const,
  },
  media: {
    all: ['media'] as const,
    lists: () => ['media', 'list'] as const,
    list: (params?: Record<string, any>) => ['media', 'list', params] as const,
    folders: ['media', 'folders'] as const,
    folder: (id: string) => ['media', 'folders', id] as const,
    orphans: (params?: Record<string, any>) => ['media', 'orphans', params] as const,
    detail: (id: string) => ['media', 'detail', id] as const,
  },
  seo: {
    all: ['seo'] as const,
    detail: (entityType: string, entityId: string) => ['seo', entityType, entityId] as const,
    settings: ['seo', 'settings'] as const,
  },
  artists: {
    all: ['artists'] as const,
    lists: () => ['artists', 'list'] as const,
    list: (params?: Record<string, any>) => ['artists', 'list', params] as const,
    detail: (id: string) => ['artists', 'detail', id] as const,
    media: (artistId: string) => ['artists', 'media', artistId] as const,
    products: (productId: string) => ['products', 'artists', productId] as const,
  },
  antiques: {
    all: ['antiques'] as const,
    lists: () => ['antiques', 'list'] as const,
    list: (params?: Record<string, any>) => ['antiques', 'list', params] as const,
    profile: (productId: string) => ['antiques', 'profile', productId] as const,
  },
  sanskritEdit: {
    all: ['sanskrit-edit'] as const,
    lists: () => ['sanskrit-edit', 'list'] as const,
    list: (params?: Record<string, any>) => ['sanskrit-edit', 'list', params] as const,
    profile: (productId: string) => ['sanskrit-edit', 'profile', productId] as const,
  },
  homepage: {
    all: ['homepage'] as const,
    lists: () => ['homepage', 'list'] as const,
    list: (params?: Record<string, any>) => ['homepage', 'list', params] as const,
    detail: (id: string) => ['homepage', 'detail', id] as const,
    sections: (homepageId: string) => ['homepage', 'sections', homepageId] as const,
    section: (homepageId: string, sectionId: string) =>
      ['homepage', 'sections', homepageId, sectionId] as const,
  },
  journal: {
    all: ['journal'] as const,
    posts: () => ['journal', 'posts'] as const,
    postList: (params?: Record<string, any>) => ['journal', 'posts', params] as const,
    post: (id: string) => ['journal', 'post', id] as const,
    authors: (params?: Record<string, any>) => ['journal', 'authors', params] as const,
    author: (id: string) => ['journal', 'author', id] as const,
    categories: (params?: Record<string, any>) => ['journal', 'categories', params] as const,
    category: (id: string) => ['journal', 'category', id] as const,
    tags: (params?: Record<string, any>) => ['journal', 'tags', params] as const,
    tag: (id: string) => ['journal', 'tag', id] as const,
  },
};
